FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow==2.16.2

EXPOSE 5000
# Backend SQLite + artefacts servis par le serveur (proxy artifacts) -> aucune DB externe
CMD ["mlflow", "server", \
     "--host", "0.0.0.0", "--port", "5000", \
     "--backend-store-uri", "sqlite:////mlflow/backend.db", \
     "--artifacts-destination", "/mlflow/mlruns", \
     "--serve-artifacts"]
